name: Playwright Tests
on: pull_request

jobs:
  prepare_app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install root dependencies
        run: pnpm install --frozen-lockfile
      - name: Build ci
        run: pnpm run build:ci
      - name: Upload build
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: build

  e2e_chrome:
    needs: prepare_app
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: e2e
    steps:
      - uses: actions/checkout@v4
      - name: Download build
        uses: actions/download-artifact@v3
        with:
          name: build
          path: build
      - name: Copy e2e envs
        run: cp .env.dist .env
      - name: Install e2e dependencies
        run: pnpm install --frozen-lockfile
      - name: Run build and tests
        run: pnpm run test:chrome
      - name: Upload test results
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: e2e-chrome-artifacts
          path: |
            e2e/test-report/
            e2e/test-results/
          retention-days: 30

  e2e_firefox:
    needs: prepare_app
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: e2e
    steps:
      - uses: actions/checkout@v4
      - name: Download build
        uses: actions/download-artifact@v3
        with:
          name: build
          path: build
      - name: Copy e2e envs
        run: cp .env.dist .env
      - name: Install e2e dependencies
        run: pnpm install --frozen-lockfile
      - name: Run build and tests
        run: pnpm run test:firefox
      - name: Upload test results
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: e2e-firefox-artifacts
          path: |
            e2e/test-report/
            e2e/test-results/
          retention-days: 30

  e2e_safari:
    needs: prepare_app
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: e2e
    steps:
      - uses: actions/checkout@v4
      - name: Download build
        uses: actions/download-artifact@v3
        with:
          name: build
          path: build
      - name: Copy e2e envs
        run: cp .env.dist .env
      - name: Install e2e dependencies
        run: pnpm install --frozen-lockfile
      - name: Run build and tests
        run: pnpm run test:safari
      - name: Upload test results
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: e2e-safari-artifacts
          path: |
            e2e/test-report/
            e2e/test-results/
          retention-days: 30