name: e2e Tests
on: pull_request

jobs:
  prepare_app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          run_install: false
      - name: Install root dependencies
        run: pnpm install --frozen-lockfile
      - name: Build ci
        run: pnpm run build:ci
      - name: Upload build
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: dist
  e2e:
    needs: prepare_app
    runs-on: ubuntu-latest
    strategy:
      matrix:
        browser: [chrome, firefox, safari]
    defaults:
      run:
        working-directory: e2e
    steps:
      - uses: actions/checkout@v4
      - name: Download build
        uses: actions/download-artifact@v4
        with:
          name: build
          path: dist
      - name: Copy e2e envs
        run: cp .env.dist .env
      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          run_install: false
      - name: Install e2e dependencies
        run: pnpm install --frozen-lockfile
      - name: Run build and tests for ${{ matrix.browser }}
        run: pnpm run test:${{ matrix.browser }}
      - name: Upload test results for ${{ matrix.browser }}
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: e2e-${{ matrix.browser }}-artifacts
          path: |
            e2e/test-report/
            e2e/test-results/
          retention-days: 30